apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alproject
resources:
  - namespace.yaml
  - portal-secret.yaml
  - portal.yaml
  - agent-hub-gateway.yaml
  - hello-lab.yaml
